package jma

var Weathers = map[string]Weather{
	"100": {Code: "100", Category: Sunny, IconSVGDay: "100.svg", IconSVGNight: "500.svg", TextJa: "晴", TextEn: "CLEAR", Emoji: Emoji{":sunny:", "☀️"}},
	"101": {Code: "101", Category: Sunny, IconSVGDay: "101.svg", IconSVGNight: "501.svg", TextJa: "晴時々曇", TextEn: "PARTLY CLOUDY", Emoji: Emoji{":mostly_sunny:", "🌤"}},
	"102": {Code: "102", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴一時雨", TextEn: "CLEAR, OCCASIONAL SCATTERED SHOWERS", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"103": {Code: "103", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴時々雨", TextEn: "CLEAR, FREQUENT SCATTERED SHOWERS", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"104": {Code: "104", Category: Snowy, IconSVGDay: "104.svg", IconSVGNight: "504.svg", TextJa: "晴一時雪", TextEn: "CLEAR, SNOW FLURRIES", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"105": {Code: "105", Category: Snowy, IconSVGDay: "104.svg", IconSVGNight: "504.svg", TextJa: "晴時々雪", TextEn: "CLEAR, FREQUENT SNOW FLURRIES", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"106": {Code: "106", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴一時雨か雪", TextEn: "CLEAR, OCCASIONAL SCATTERED SHOWERS OR SNOW FLURRIES", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"107": {Code: "107", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴時々雨か雪", TextEn: "CLEAR, FREQUENT SCATTERED SHOWERS OR SNOW FLURRIES", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"108": {Code: "108", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴一時雨か雷雨", TextEn: "CLEAR, OCCASIONAL SCATTERED SHOWERS AND/OR THUNDER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"110": {Code: "110", Category: Sunny, IconSVGDay: "110.svg", IconSVGNight: "510.svg", TextJa: "晴後時々曇", TextEn: "CLEAR, PARTLY CLOUDY LATER", Emoji: Emoji{":partly_sunny:", "⛅️"}},
	"111": {Code: "111", Category: Sunny, IconSVGDay: "110.svg", IconSVGNight: "510.svg", TextJa: "晴後曇", TextEn: "CLEAR, CLOUDY LATER", Emoji: Emoji{":partly_sunny:", "⛅️"}},
	"112": {Code: "112", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴後一時雨", TextEn: "CLEAR, OCCASIONAL SCATTERED SHOWERS LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"113": {Code: "113", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴後時々雨", TextEn: "CLEAR, FREQUENT SCATTERED SHOWERS LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"114": {Code: "114", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴後雨", TextEn: "CLEAR,RAIN LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"115": {Code: "115", Category: Snowy, IconSVGDay: "115.svg", IconSVGNight: "515.svg", TextJa: "晴後一時雪", TextEn: "CLEAR, OCCASIONAL SNOW FLURRIES LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"116": {Code: "116", Category: Snowy, IconSVGDay: "115.svg", IconSVGNight: "515.svg", TextJa: "晴後時々雪", TextEn: "CLEAR, FREQUENT SNOW FLURRIES LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"117": {Code: "117", Category: Snowy, IconSVGDay: "115.svg", IconSVGNight: "515.svg", TextJa: "晴後雪", TextEn: "CLEAR,SNOW LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"118": {Code: "118", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴後雨か雪", TextEn: "CLEAR, RAIN OR SNOW LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"119": {Code: "119", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴後雨か雷雨", TextEn: "CLEAR, RAIN AND/OR THUNDER LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"120": {Code: "120", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴朝夕一時雨", TextEn: "OCCASIONAL SCATTERED SHOWERS IN THE MORNING AND EVENING, CLEAR DURING THE DAY", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"121": {Code: "121", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴朝の内一時雨", TextEn: "OCCASIONAL SCATTERED SHOWERS IN THE MORNING, CLEAR DURING THE DAY", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"122": {Code: "122", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴夕方一時雨", TextEn: "CLEAR, OCCASIONAL SCATTERED SHOWERS IN THE EVENING", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"123": {Code: "123", Category: Sunny, IconSVGDay: "100.svg", IconSVGNight: "500.svg", TextJa: "晴山沿い雷雨", TextEn: "CLEAR IN THE PLAINS, RAIN AND THUNDER NEAR MOUTAINOUS AREAS", Emoji: Emoji{":sunny:", "☀️"}},
	"124": {Code: "124", Category: Sunny, IconSVGDay: "100.svg", IconSVGNight: "500.svg", TextJa: "晴山沿い雪", TextEn: "CLEAR IN THE PLAINS, SNOW NEAR MOUTAINOUS AREAS", Emoji: Emoji{":sunny:", "☀️"}},
	"125": {Code: "125", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴午後は雷雨", TextEn: "CLEAR, RAIN AND THUNDER IN THE AFTERNOON", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"126": {Code: "126", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴昼頃から雨", TextEn: "CLEAR, RAIN IN THE AFTERNOON", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"127": {Code: "127", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴夕方から雨", TextEn: "CLEAR, RAIN IN THE EVENING", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"128": {Code: "128", Category: Rainy, IconSVGDay: "112.svg", IconSVGNight: "512.svg", TextJa: "晴夜は雨", TextEn: "CLEAR, RAIN IN THE NIGHT", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"130": {Code: "130", Category: Sunny, IconSVGDay: "100.svg", IconSVGNight: "500.svg", TextJa: "朝の内霧後晴", TextEn: "FOG IN THE MORNING, CLEAR LATER", Emoji: Emoji{":sunny:", "☀️"}},
	"131": {Code: "131", Category: Sunny, IconSVGDay: "100.svg", IconSVGNight: "500.svg", TextJa: "晴明け方霧", TextEn: "FOG AROUND DAWN, CLEAR LATER", Emoji: Emoji{":sunny:", "☀️"}},
	"132": {Code: "132", Category: Sunny, IconSVGDay: "101.svg", IconSVGNight: "501.svg", TextJa: "晴朝夕曇", TextEn: "CLOUDY IN THE MORNING AND EVENING, CLEAR DURING THE DAY", Emoji: Emoji{":mostly_sunny:", "🌤"}},
	"140": {Code: "140", Category: Rainy, IconSVGDay: "102.svg", IconSVGNight: "502.svg", TextJa: "晴時々雨で雷を伴う", TextEn: "CLEAR, FREQUENT SCATTERED SHOWERS AND THUNDER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"160": {Code: "160", Category: Snowy, IconSVGDay: "104.svg", IconSVGNight: "504.svg", TextJa: "晴一時雪か雨", TextEn: "CLEAR, SNOW FLURRIES OR OCCASIONAL SCATTERED SHOWERS", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"170": {Code: "170", Category: Snowy, IconSVGDay: "104.svg", IconSVGNight: "504.svg", TextJa: "晴時々雪か雨", TextEn: "CLEAR, FREQUENT SNOW FLURRIES OR SCATTERED SHOWERS", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"181": {Code: "181", Category: Snowy, IconSVGDay: "115.svg", IconSVGNight: "515.svg", TextJa: "晴後雪か雨", TextEn: "CLEAR, SNOW OR RAIN LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"200": {Code: "200", Category: Cloudy, IconSVGDay: "200.svg", IconSVGNight: "200.svg", TextJa: "曇", TextEn: "CLOUDY", Emoji: Emoji{":cloud:", "☁️"}},
	"201": {Code: "201", Category: Cloudy, IconSVGDay: "201.svg", IconSVGNight: "601.svg", TextJa: "曇時々晴", TextEn: "MOSTLY CLOUDY", Emoji: Emoji{":barely_sunny:", "🌥"}},
	"202": {Code: "202", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇一時雨", TextEn: "CLOUDY, OCCASIONAL SCATTERED SHOWERS", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"203": {Code: "203", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇時々雨", TextEn: "CLOUDY, FREQUENT SCATTERED SHOWERS", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"204": {Code: "204", Category: Snowy, IconSVGDay: "204.svg", IconSVGNight: "204.svg", TextJa: "曇一時雪", TextEn: "CLOUDY, OCCASIONAL SNOW FLURRIES", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"205": {Code: "205", Category: Snowy, IconSVGDay: "204.svg", IconSVGNight: "204.svg", TextJa: "曇時々雪", TextEn: "CLOUDY FREQUENT SNOW FLURRIES", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"206": {Code: "206", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇一時雨か雪", TextEn: "CLOUDY, OCCASIONAL SCATTERED SHOWERS OR SNOW FLURRIES", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"207": {Code: "207", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇時々雨か雪", TextEn: "CLOUDY, FREQUENT SCCATERED SHOWERS OR SNOW FLURRIES", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"208": {Code: "208", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇一時雨か雷雨", TextEn: "CLOUDY, OCCASIONAL SCATTERED SHOWERS AND/OR THUNDER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"209": {Code: "209", Category: Cloudy, IconSVGDay: "200.svg", IconSVGNight: "200.svg", TextJa: "霧", TextEn: "FOG", Emoji: Emoji{":cloud:", "☁️"}},
	"210": {Code: "210", Category: Cloudy, IconSVGDay: "210.svg", IconSVGNight: "610.svg", TextJa: "曇後時々晴", TextEn: "CLOUDY, PARTLY CLOUDY LATER", Emoji: Emoji{":partly_sunny:", "⛅️"}},
	"211": {Code: "211", Category: Cloudy, IconSVGDay: "210.svg", IconSVGNight: "610.svg", TextJa: "曇後晴", TextEn: "CLOUDY, CLEAR LATER", Emoji: Emoji{":partly_sunny:", "⛅️"}},
	"212": {Code: "212", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇後一時雨", TextEn: "CLOUDY, OCCASIONAL SCATTERED SHOWERS LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"213": {Code: "213", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇後時々雨", TextEn: "CLOUDY, FREQUENT SCATTERED SHOWERS LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"214": {Code: "214", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇後雨", TextEn: "CLOUDY, RAIN LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"215": {Code: "215", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇後一時雪", TextEn: "CLOUDY, SNOW FLURRIES LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"216": {Code: "216", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇後時々雪", TextEn: "CLOUDY, FREQUENT SNOW FLURRIES LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"217": {Code: "217", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇後雪", TextEn: "CLOUDY, SNOW LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"218": {Code: "218", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇後雨か雪", TextEn: "CLOUDY, RAIN OR SNOW LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"219": {Code: "219", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇後雨か雷雨", TextEn: "CLOUDY, RAIN AND/OR THUNDER LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"220": {Code: "220", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇朝夕一時雨", TextEn: "OCCASIONAL SCCATERED SHOWERS IN THE MORNING AND EVENING, CLOUDY DURING THE DAY", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"221": {Code: "221", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇朝の内一時雨", TextEn: "CLOUDY OCCASIONAL SCCATERED SHOWERS IN THE MORNING", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"222": {Code: "222", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇夕方一時雨", TextEn: "CLOUDY, OCCASIONAL SCCATERED SHOWERS IN THE EVENING", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"223": {Code: "223", Category: Cloudy, IconSVGDay: "201.svg", IconSVGNight: "601.svg", TextJa: "曇日中時々晴", TextEn: "CLOUDY IN THE MORNING AND EVENING, PARTLY CLOUDY DURING THE DAY,", Emoji: Emoji{":barely_sunny:", "🌥"}},
	"224": {Code: "224", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇昼頃から雨", TextEn: "CLOUDY, RAIN IN THE AFTERNOON", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"225": {Code: "225", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇夕方から雨", TextEn: "CLOUDY, RAIN IN THE EVENING", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"226": {Code: "226", Category: Rainy, IconSVGDay: "212.svg", IconSVGNight: "212.svg", TextJa: "曇夜は雨", TextEn: "CLOUDY, RAIN IN THE NIGHT", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"228": {Code: "228", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇昼頃から雪", TextEn: "CLOUDY, SNOW IN THE AFTERNOON", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"229": {Code: "229", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇夕方から雪", TextEn: "CLOUDY, SNOW IN THE EVENING", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"230": {Code: "230", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇夜は雪", TextEn: "CLOUDY, SNOW IN THE NIGHT", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"231": {Code: "231", Category: Cloudy, IconSVGDay: "200.svg", IconSVGNight: "200.svg", TextJa: "曇海上海岸は霧か霧雨", TextEn: "CLOUDY, FOG OR DRIZZLING ON THE SEA AND NEAR SEASHORE", Emoji: Emoji{":cloud:", "☁️"}},
	"240": {Code: "240", Category: Rainy, IconSVGDay: "202.svg", IconSVGNight: "202.svg", TextJa: "曇時々雨で雷を伴う", TextEn: "CLOUDY, FREQUENT SCCATERED SHOWERS AND THUNDER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"250": {Code: "250", Category: Snowy, IconSVGDay: "204.svg", IconSVGNight: "204.svg", TextJa: "曇時々雪で雷を伴う", TextEn: "CLOUDY, FREQUENT SNOW AND THUNDER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"260": {Code: "260", Category: Snowy, IconSVGDay: "204.svg", IconSVGNight: "204.svg", TextJa: "曇一時雪か雨", TextEn: "CLOUDY, SNOW FLURRIES OR OCCASIONAL SCATTERED SHOWERS", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"270": {Code: "270", Category: Snowy, IconSVGDay: "204.svg", IconSVGNight: "204.svg", TextJa: "曇時々雪か雨", TextEn: "CLOUDY, FREQUENT SNOW FLURRIES OR SCATTERED SHOWERS", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"281": {Code: "281", Category: Snowy, IconSVGDay: "215.svg", IconSVGNight: "215.svg", TextJa: "曇後雪か雨", TextEn: "CLOUDY, SNOW OR RAIN LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"300": {Code: "300", Category: Rainy, IconSVGDay: "300.svg", IconSVGNight: "300.svg", TextJa: "雨", TextEn: "RAIN", Emoji: Emoji{":umbrella:", "☂️"}},
	"301": {Code: "301", Category: Rainy, IconSVGDay: "301.svg", IconSVGNight: "701.svg", TextJa: "雨時々晴", TextEn: "RAIN, PARTLY CLOUDY", Emoji: Emoji{":umbrella:", "☂️"}},
	"302": {Code: "302", Category: Rainy, IconSVGDay: "302.svg", IconSVGNight: "302.svg", TextJa: "雨時々止む", TextEn: "SHOWERS THROUGHOUT THE DAY", Emoji: Emoji{":umbrella:", "☂️"}},
	"303": {Code: "303", Category: Snowy, IconSVGDay: "303.svg", IconSVGNight: "303.svg", TextJa: "雨時々雪", TextEn: "RAIN,FREQUENT SNOW FLURRIES", Emoji: Emoji{":umbrella:", "☂️"}},
	"304": {Code: "304", Category: Rainy, IconSVGDay: "300.svg", IconSVGNight: "300.svg", TextJa: "雨か雪", TextEn: "RAINORSNOW", Emoji: Emoji{":umbrella:", "☂️"}},
	"306": {Code: "306", Category: Rainy, IconSVGDay: "300.svg", IconSVGNight: "300.svg", TextJa: "大雨", TextEn: "HEAVYRAIN", Emoji: Emoji{":umbrella:", "☂️"}},
	"308": {Code: "308", Category: Rainy, IconSVGDay: "308.svg", IconSVGNight: "308.svg", TextJa: "雨で暴風を伴う", TextEn: "RAINSTORM", Emoji: Emoji{":umbrella_with_rain_drops:", "☔️"}},
	"309": {Code: "309", Category: Snowy, IconSVGDay: "303.svg", IconSVGNight: "303.svg", TextJa: "雨一時雪", TextEn: "RAIN,OCCASIONAL SNOW", Emoji: Emoji{":umbrella:", "☂️"}},
	"311": {Code: "311", Category: Rainy, IconSVGDay: "311.svg", IconSVGNight: "711.svg", TextJa: "雨後晴", TextEn: "RAIN,CLEAR LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"313": {Code: "313", Category: Rainy, IconSVGDay: "313.svg", IconSVGNight: "313.svg", TextJa: "雨後曇", TextEn: "RAIN,CLOUDY LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"314": {Code: "314", Category: Snowy, IconSVGDay: "314.svg", IconSVGNight: "314.svg", TextJa: "雨後時々雪", TextEn: "RAIN, FREQUENT SNOW FLURRIES LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"315": {Code: "315", Category: Snowy, IconSVGDay: "314.svg", IconSVGNight: "314.svg", TextJa: "雨後雪", TextEn: "RAIN,SNOW LATER", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"316": {Code: "316", Category: Rainy, IconSVGDay: "311.svg", IconSVGNight: "711.svg", TextJa: "雨か雪後晴", TextEn: "RAIN OR SNOW, CLEAR LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"317": {Code: "317", Category: Rainy, IconSVGDay: "313.svg", IconSVGNight: "313.svg", TextJa: "雨か雪後曇", TextEn: "RAIN OR SNOW, CLOUDY LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"320": {Code: "320", Category: Rainy, IconSVGDay: "311.svg", IconSVGNight: "711.svg", TextJa: "朝の内雨後晴", TextEn: "RAIN IN THE MORNING, CLEAR LATER", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"321": {Code: "321", Category: Rainy, IconSVGDay: "313.svg", IconSVGNight: "313.svg", TextJa: "朝の内雨後曇", TextEn: "RAIN IN THE MORNING, CLOUDY LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"322": {Code: "322", Category: Snowy, IconSVGDay: "303.svg", IconSVGNight: "303.svg", TextJa: "雨朝晩一時雪", TextEn: "OCCASIONAL SNOW IN THE MORNING AND EVENING, RAIN DURING THE DAY", Emoji: Emoji{":umbrella:", "☂️"}},
	"323": {Code: "323", Category: Rainy, IconSVGDay: "311.svg", IconSVGNight: "711.svg", TextJa: "雨昼頃から晴", TextEn: "RAIN, CLEAR IN THE AFTERNOON", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"324": {Code: "324", Category: Rainy, IconSVGDay: "311.svg", IconSVGNight: "711.svg", TextJa: "雨夕方から晴", TextEn: "RAIN, CLEAR IN THE EVENING", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"325": {Code: "325", Category: Rainy, IconSVGDay: "311.svg", IconSVGNight: "711.svg", TextJa: "雨夜は晴", TextEn: "RAIN, CLEAR IN THE NIGHT", Emoji: Emoji{":partly_sunny_rain:", "🌦"}},
	"326": {Code: "326", Category: Snowy, IconSVGDay: "314.svg", IconSVGNight: "314.svg", TextJa: "雨夕方から雪", TextEn: "RAIN, SNOW IN THE EVENING", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"327": {Code: "327", Category: Snowy, IconSVGDay: "314.svg", IconSVGNight: "314.svg", TextJa: "雨夜は雪", TextEn: "RAIN,SNOW IN THE NIGHT", Emoji: Emoji{":snow_cloud:", "🌨"}},
	"328": {Code: "328", Category: Rainy, IconSVGDay: "300.svg", IconSVGNight: "300.svg", TextJa: "雨一時強く降る", TextEn: "RAIN, EXPECT OCCASIONAL HEAVY RAINFALL", Emoji: Emoji{":umbrella:", "☂️"}},
	"329": {Code: "329", Category: Rainy, IconSVGDay: "300.svg", IconSVGNight: "300.svg", TextJa: "雨一時みぞれ", TextEn: "RAIN, OCCASIONAL SLEET", Emoji: Emoji{":umbrella:", "☂️"}},
	"340": {Code: "340", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "雪か雨", TextEn: "SNOWORRAIN", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
	"350": {Code: "350", Category: Rainy, IconSVGDay: "300.svg", IconSVGNight: "300.svg", TextJa: "雨で雷を伴う", TextEn: "RAIN AND THUNDER", Emoji: Emoji{":umbrella:", "☂️"}},
	"361": {Code: "361", Category: Snowy, IconSVGDay: "411.svg", IconSVGNight: "811.svg", TextJa: "雪か雨後晴", TextEn: "SNOW OR RAIN, CLEAR LATER", Emoji: Emoji{":snowflake:", "❄️"}},
	"371": {Code: "371", Category: Snowy, IconSVGDay: "413.svg", IconSVGNight: "413.svg", TextJa: "雪か雨後曇", TextEn: "SNOW OR RAIN, CLOUDY LATER", Emoji: Emoji{":snowflake:", "❄️"}},
	"400": {Code: "400", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "雪", TextEn: "SNOW", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
	"401": {Code: "401", Category: Snowy, IconSVGDay: "401.svg", IconSVGNight: "801.svg", TextJa: "雪時々晴", TextEn: "SNOW, FREQUENT CLEAR", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"402": {Code: "402", Category: Snowy, IconSVGDay: "402.svg", IconSVGNight: "402.svg", TextJa: "雪時々止む", TextEn: "SNOWTHROUGHOUT THE DAY", Emoji: Emoji{":snowflake:", "❄️"}},
	"403": {Code: "403", Category: Snowy, IconSVGDay: "403.svg", IconSVGNight: "403.svg", TextJa: "雪時々雨", TextEn: "SNOW,FREQUENT SCCATERED SHOWERS", Emoji: Emoji{":rain_cloud:", "🌨"}},
	"405": {Code: "405", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "大雪", TextEn: "HEAVYSNOW", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
	"406": {Code: "406", Category: Snowy, IconSVGDay: "406.svg", IconSVGNight: "406.svg", TextJa: "風雪強い", TextEn: "SNOWSTORM", Emoji: Emoji{":snowman:", "☃️"}},
	"407": {Code: "407", Category: Snowy, IconSVGDay: "406.svg", IconSVGNight: "406.svg", TextJa: "暴風雪", TextEn: "HEAVYSNOWSTORM", Emoji: Emoji{":snowman:", "☃️"}},
	"409": {Code: "409", Category: Snowy, IconSVGDay: "403.svg", IconSVGNight: "403.svg", TextJa: "雪一時雨", TextEn: "SNOW, OCCASIONAL SCCATERED SHOWERS", Emoji: Emoji{":rain_cloud:", "🌨"}},
	"411": {Code: "411", Category: Snowy, IconSVGDay: "411.svg", IconSVGNight: "811.svg", TextJa: "雪後晴", TextEn: "SNOW,CLEAR LATER", Emoji: Emoji{":snowflake:", "❄️"}},
	"413": {Code: "413", Category: Snowy, IconSVGDay: "413.svg", IconSVGNight: "413.svg", TextJa: "雪後曇", TextEn: "SNOW,CLOUDY LATER", Emoji: Emoji{":snowflake:", "❄️"}},
	"414": {Code: "414", Category: Snowy, IconSVGDay: "414.svg", IconSVGNight: "414.svg", TextJa: "雪後雨", TextEn: "SNOW,RAIN LATER", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"420": {Code: "420", Category: Snowy, IconSVGDay: "411.svg", IconSVGNight: "811.svg", TextJa: "朝の内雪後晴", TextEn: "SNOW IN THE MORNING, CLEAR LATER", Emoji: Emoji{":snowflake:", "❄️"}},
	"421": {Code: "421", Category: Snowy, IconSVGDay: "413.svg", IconSVGNight: "413.svg", TextJa: "朝の内雪後曇", TextEn: "SNOW IN THE MORNING, CLOUDY LATER", Emoji: Emoji{":snowflake:", "❄️"}},
	"422": {Code: "422", Category: Snowy, IconSVGDay: "414.svg", IconSVGNight: "414.svg", TextJa: "雪昼頃から雨", TextEn: "SNOW, RAIN IN THE AFTERNOON", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"423": {Code: "423", Category: Snowy, IconSVGDay: "414.svg", IconSVGNight: "414.svg", TextJa: "雪夕方から雨", TextEn: "SNOW, RAIN IN THE EVENING", Emoji: Emoji{":rain_cloud:", "🌧"}},
	"425": {Code: "425", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "雪一時強く降る", TextEn: "SNOW, EXPECT OCCASIONAL HEAVY SNOWFALL", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
	"426": {Code: "426", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "雪後みぞれ", TextEn: "SNOW, SLEET LATER", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
	"427": {Code: "427", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "雪一時みぞれ", TextEn: "SNOW, OCCASIONAL SLEET", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
	"450": {Code: "450", Category: Snowy, IconSVGDay: "400.svg", IconSVGNight: "400.svg", TextJa: "雪で雷を伴う", TextEn: "SNOW AND THUNDER", Emoji: Emoji{":snowman_without_snow:", "⛄️"}},
}
